# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Test-Manifest
version:      1.13
version_from: lib/Manifest.pm
installdirs:  site
requires:
    ExtUtils::MakeMaker:           6.03
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.23
