--- #YAML:1.0
name:                Test-Manifest
version:             1.22
abstract:            interact with a t/test_manifest file
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    ExtUtils::MakeMaker:           6.03
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
