---
abstract: 'Interact with a t/test_manifest file'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.86, CPAN::Meta::Converter version 2.120921'
keywords:
  - module
  - distribution
  - test
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Test-Manifest
no_index:
  directory:
    - t
    - inc
requires:
  Test::More: 0.95
  perl: 5.006
resources:
  bugtracker: http://rt.cpan.org/NoAuth/Bugs.html?Dist=Test-Manifest
  repository: git://github.com/briandfoy/test-manifest.git
version: 2.02
