--- #YAML:1.0
name:                Test-Manifest
version:             1.17
abstract:            ~
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.31
distribution_type:   module
requires:     
    ExtUtils::MakeMaker:           6.03
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
author:
    - brian d foy <bdfoy@cpan.org>
